Repository openshift/backplane-cli, pull requests merged in 2023-03, with the labels that each got.

#25 Migrate backplane-cli: console
  cmd/ocm-backplane/console/console.go
  cmd/ocm-backplane/console/console_suite_test.go
  cmd/ocm-backplane/console/console_test.go
  cmd/ocm-backplane/root.go
  go.mod
  go.sum
Labels: lgtm, approved

#30 fix panic when the error returned is not the backplane error struct
  pkg/utils/util.go
Labels: lgtm, approved

#35 OSD-15451: Fix failing backplane unit tests and update kubeconfig read/write tests
  Makefile
  cmd/ocm-backplane/cloud/console_test.go
  cmd/ocm-backplane/cloud/credentials_test.go
  cmd/ocm-backplane/console/console_suite_test.go
  cmd/ocm-backplane/console/console_test.go
  cmd/ocm-backplane/login/login_suite_test.go
  cmd/ocm-backplane/login/login_test.go
  cmd/ocm-backplane/logout/logout_test.go
  cmd/ocm-backplane/script/describeScript_test.go
  cmd/ocm-backplane/script/listScripts_test.go
  cmd/ocm-backplane/testJob/createTestJob_test.go
  cmd/ocm-backplane/testJob/getTestJob_test.go
  pkg/utils/cluster_test.go
  pkg/utils/util.go
Labels: lgtm, approved, jira/valid-reference, tide/merge-method-squash

#36 Add codecov, go reference and license badges
  README.md
Labels: lgtm, approved

#37 Added check for env KUBE_PS1_CLUSTER_FUNCTION
  cmd/ocm-backplane/login/login.go
Labels: lgtm, approved

#40 Add flag to login to managing cluster instead of target cluster
  cmd/ocm-backplane/login/login.go
  cmd/ocm-backplane/login/login_test.go
  pkg/utils/mocks/ocmWrapperMock.go
  pkg/utils/ocmWrapper.go
Labels: lgtm, approved

#42 OSD-15452 : Updating Readme
  README.md
Labels: lgtm, approved

#38 Add elevate command
  README.md
  cmd/ocm-backplane/elevate/elevate.go
  cmd/ocm-backplane/root.go
  pkg/elevate/elevate.go
  pkg/elevate/elevate_test.go
Labels: lgtm, approved

#43 Update how to enable kube-ps1 plugin in Zsh
  docs/PS1-setup.md
Labels: lgtm, approved

#44 OSD-15582: Fix backplane-api server regex
  pkg/utils/util.go
Labels: lgtm, approved, jira/valid-reference

#45 OSD-15582: Make backplane-api server regex loosely restricted
  pkg/utils/util.go
Labels: lgtm, approved, jira/valid-reference

#47 OSD-15550 - Add error handling and unit test for empty list of scripts
  cmd/ocm-backplane/script/listScripts.go
  cmd/ocm-backplane/script/listScripts_test.go
Labels: lgtm, approved

#48 Tweak regex to conform to prod URL
  pkg/utils/util.go
Labels: lgtm, approved

#46 OSD-15567: Add Proxy URL support to login command
  cmd/ocm-backplane/cloud/console.go
  cmd/ocm-backplane/cloud/console_test.go
  cmd/ocm-backplane/cloud/credentials.go
  cmd/ocm-backplane/cloud/credentials_test.go
  cmd/ocm-backplane/login/login.go
  cmd/ocm-backplane/login/login_test.go
  cmd/ocm-backplane/managedJob/createManagedJob_test.go
  cmd/ocm-backplane/managedJob/deleteManagedJob.go
  cmd/ocm-backplane/managedJob/deleteManagedJob_test.go
  cmd/ocm-backplane/managedJob/getManagedJob.go
  cmd/ocm-backplane/managedJob/getManagedJob_test.go
  cmd/ocm-backplane/managedJob/logsManagedJob.go
  cmd/ocm-backplane/script/describeScript.go
  cmd/ocm-backplane/script/describeScript_test.go
  cmd/ocm-backplane/script/listScripts.go
  cmd/ocm-backplane/script/listScripts_test.go
  cmd/ocm-backplane/testJob/createTestJob.go
  cmd/ocm-backplane/testJob/createTestJob_test.go
  cmd/ocm-backplane/testJob/getTestJob.go
  cmd/ocm-backplane/testJob/getTestJobLogs.go
  cmd/ocm-backplane/testJob/getTestJob_test.go
  go.mod
  pkg/cli/config/config.go
  pkg/cli/config/config_test.go
  pkg/cli/globalflags/globalflags.go
  pkg/info/info.go
  pkg/utils/clientUtils.go
  pkg/utils/cluster.go
  pkg/utils/cluster_test.go
  pkg/utils/mocks/clientUtilsMock.go
  pkg/utils/mocks/ocmWrapperMock.go
  pkg/utils/ocmWrapper.go
  pkg/utils/util_test.go
Labels: lgtm, approved, jira/valid-reference

#52 login fix
  .gitignore
  cmd/ocm-backplane/login/login.go
  cmd/ocm-backplane/login/login_test.go
  pkg/cli/config/config.go
Labels: lgtm, approved

#54 Bug fix: proxy-url not exists after login
  cmd/ocm-backplane/login/login.go
Labels: lgtm, approved

#53 OSD-15495 - Add method to check if the container is already running
  cmd/ocm-backplane/console/console.go
Labels: lgtm, approved

#60 Fix upgrade and version check
  .goreleaser.yaml
  cmd/ocm-backplane/version/version.go
  internal/github/github.go
  internal/github/github_test.go
  internal/upgrade/upgrade.go
  pkg/info/info.go
Labels: lgtm, approved, tide/merge-method-squash

#57 Change config file name
  pkg/cli/config/config.go
  pkg/cli/config/config_test.go
  pkg/info/info.go
Labels: lgtm, approved

#61 OSD-15552: Add ocm-token to kubeconfig
  cmd/ocm-backplane/login/login.go
  cmd/ocm-backplane/login/login_test.go
  docs/PS1-setup.md
Labels: lgtm, approved, jira/valid-reference

#62 Update documentation
  README.md
Labels: lgtm, approved
