Repository openshift/backplane-cli, pull requests merged in 2023-01, with the labels that each got.

#1 Adding OWNERS file to bp-cli
  OWNERS
Labels: lgtm

#2 OSD-14676 : Initializing bp-cli repo
  Dockerfile
  Makefile
  README.md
  cmd/ocm-backplane/hello/hello.go
  cmd/ocm-backplane/hello/hello_test.go
  cmd/ocm-backplane/main.go
  cmd/ocm-backplane/root.go
  go.mod
  go.sum
  golangci.yml
  make.Dockerfile
Labels: lgtm, approved

#3 Add OpenAPI client
  Makefile
  docs/backplane-api.yaml
  go.mod
  go.sum
  openapi.Dockerfile
  pkg/client/BackplaneApi.go
Labels: lgtm, approved, tide/merge-method-squash

#4 OSD-14993: Automate backplane-cli release cycle
  .gitignore
  .goreleaser.yaml
  Makefile
  docs/release.md
Labels: lgtm, approved, jira/valid-reference
