Repository openshift/backplane-cli, pull requests merged in 2023-06, with the labels that each got.

#120 OSD-16073 backplane-cli support for monitoring stack for layered…
  README.md
  cmd/ocm-backplane/monitoring/monitoring.go
  cmd/ocm-backplane/root.go
  pkg/monitoring/monitoring.go
  pkg/monitoring/monitoring_suite_test.go
  pkg/monitoring/monitoring_test.go
Labels: lgtm, approved

#126 typo fixes and updates some of the variable names to match golang convention
  cmd/ocm-backplane/console/console.go
  cmd/ocm-backplane/console/console_test.go
  cmd/ocm-backplane/login/login.go
  cmd/ocm-backplane/status/status.go
  pkg/cli/config/config.go
  pkg/cli/session/session.go
  pkg/utils/clientUtils.go
  pkg/utils/cluster.go
  pkg/utils/renderingutils.go
  pkg/utils/util.go
Labels: lgtm, approved

#125 fix the golangci yml name
  .golangci.yml
  cmd/ocm-backplane/cloud/credentials_test.go
  cmd/ocm-backplane/testJob/createTestJob_test.go
  pkg/elevate/elevate_test.go
  pkg/monitoring/monitoring.go
Labels: lgtm, approved

#127 OSD-15841: Check proxy and API connection if login failed
  cmd/ocm-backplane/login/login.go
  cmd/ocm-backplane/login/login_test.go
  pkg/cli/config/config.go
  pkg/cli/config/config_test.go
Labels: lgtm, approved, jira/valid-reference

#121 Fix typo in README
  README.md
Labels: lgtm, approved, tide/merge-method-squash, ok-to-test

#133 Fix formatting of a couple error messages
  cmd/ocm-backplane/login/login.go
  cmd/ocm-backplane/login/login_test.go
Labels: lgtm, approved

#114 Add commands to get an STS token for a role from an ocm token, and to assume roles through a chain of ARNs
  cmd/ocm-backplane/cloud/assume.go
  cmd/ocm-backplane/cloud/cloud.go
  cmd/ocm-backplane/cloud/token.go
  go.mod
  go.sum
  pkg/awsUtil/credentials.go
  pkg/awsUtil/credentials_test.go
  pkg/awsUtil/sts.go
  pkg/awsUtil/sts_test.go
  pkg/client/mocks/ClientMock.go
  pkg/client/mocks/ClientWithResponsesMock.go
  pkg/utils/jwt.go
  pkg/utils/jwt_test.go
Labels: lgtm, approved
