Repository openshift/backplane-cli, pull requests merged in 2023-07, with the labels that each got.

#137 OSD-16244: Add error message if management cluster is not belong to same ocm env
  cmd/ocm-backplane/login/login_test.go
  pkg/utils/ocmWrapper.go
Labels: lgtm, approved, jira/valid-reference

#139 OSD-17209: Update backplane cli commands default to warning log level
  cmd/ocm-backplane/root.go
  cmd/ocm-backplane/root_suite_test.go
  cmd/ocm-backplane/root_test.go
  pkg/cli/globalflags/logs.go
Labels: lgtm, approved, jira/valid-reference

#140 refactor: update help text
  cmd/ocm-backplane/cloud/cloud.go
  cmd/ocm-backplane/console/console.go
  cmd/ocm-backplane/managedJob/managedJob.go
  cmd/ocm-backplane/script/script.go
  cmd/ocm-backplane/session/session.go
  cmd/ocm-backplane/upgrade/upgrade.go
  cmd/ocm-backplane/version/version.go
Labels: lgtm, approved

#136 Set up retries for assume role chain calls
  pkg/awsUtil/sts.go
Labels: lgtm, approved

#141 add team thor members as reviewer
  OWNERS
Labels: lgtm, approved

#144 Add service and manager flags to backplane session
  cmd/ocm-backplane/session/session.go
  pkg/cli/session/session.go
Labels: lgtm, approved

#147 OSD-16604: Add managed script wait flag until the job is finished
  cmd/ocm-backplane/managedJob/createManagedJob.go
  cmd/ocm-backplane/managedJob/createManagedJob_test.go
Labels: lgtm, approved, jira/valid-reference

#148 Refactor: Make manager & service flags global
  README.md
  cmd/ocm-backplane/login/login.go
  cmd/ocm-backplane/login/login_test.go
  cmd/ocm-backplane/session/session.go
  pkg/cli/globalflags/globalflags.go
Labels: lgtm, approved

#151 OSD-17374: Fixed backplane error overwriting issue when the proxy is not available
  cmd/ocm-backplane/login/login_test.go
  pkg/cli/config/config.go
Labels: lgtm, approved, jira/valid-reference

#149 OSD-12531: Replacing GetScripts with new GetScriptsByCluster API calls
  cmd/ocm-backplane/script/describeScript.go
  cmd/ocm-backplane/script/describeScript_test.go
  cmd/ocm-backplane/script/listScripts.go
  cmd/ocm-backplane/script/listScripts_test.go
Labels: lgtm, approved, jira/valid-reference

#152 [OSD-16605] streaming logs for managedjob
  cmd/ocm-backplane/managedJob/createManagedJob.go
  cmd/ocm-backplane/managedJob/createManagedJob_test.go
Labels: lgtm, approved

#159 Fix usage of global opts in backplane session
  cmd/ocm-backplane/session/session.go
  pkg/cli/session/session.go
  pkg/cli/session/session_test.go
Labels: lgtm, approved

#158 Added a timeout condition which will throw a timeout error whenever the server of backplane-api is down
  internal/github/github.go
  internal/github/github_test.go
Labels: lgtm, approved, tide/merge-method-squash

#162 fix: nil pointer dereference when getting cloud credentials
  cmd/ocm-backplane/cloud/credentials.go
Labels: lgtm, approved
