Repository openshift/backplane-cli, pull requests merged in 2023-02, with the labels that each got.

#5 OSD-14677: Added backplane-cli upgrade based on the latest version
  cmd/ocm-backplane/root.go
  cmd/ocm-backplane/upgrade/upgrade.go
  go.mod
  go.sum
  internal/github/github.go
  internal/github/github_test.go
  internal/github/options.go
  internal/upgrade/options.go
  internal/upgrade/upgrade.go
  internal/upgrade/writer.go
  pkg/info/info.go
Labels: lgtm, approved, jira/valid-reference

#6 Revert "Add OpenAPI client"
  Makefile
  docs/backplane-api.yaml
  go.mod
  go.sum
  openapi.Dockerfile
  pkg/client/BackplaneApi.go
Labels: lgtm, approved, tide/merge-method-squash

#10 Migrate essential packages
  .gitignore
  Makefile
  cmd/ocm-backplane/hello/hello.go
  cmd/ocm-backplane/hello/hello_test.go
  cmd/ocm-backplane/root.go
  go.mod
  go.sum
  pkg/client/mocks/ClientMock.go
  pkg/client/mocks/ClientWithResponsesMock.go
  pkg/info/info.go
  pkg/utils/clientUtils.go
  pkg/utils/cluster.go
  pkg/utils/cluster_test.go
  pkg/utils/mocks/clientUtilsMock.go
  pkg/utils/mocks/ocmWrapperMock.go
  pkg/utils/ocmWrapper.go
  pkg/utils/renderingutils.go
  pkg/utils/util.go
  pkg/utils/util_test.go
Labels: lgtm, approved, tide/merge-method-squash

#9 OSD-14684: Add Backplane cloud console and credentials commands
  cmd/ocm-backplane/cloud/cloud.go
  cmd/ocm-backplane/cloud/cloud_suite_test.go
  cmd/ocm-backplane/cloud/console.go
  cmd/ocm-backplane/cloud/console_test.go
  cmd/ocm-backplane/cloud/credentials.go
  cmd/ocm-backplane/cloud/credentials_test.go
  cmd/ocm-backplane/root.go
  go.mod
  go.sum
Labels: lgtm, approved, jira/valid-reference

#11 Add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: lgtm, approved

#15 Deprecate tunnel call in cluster.go and add BACKPLANE_CONFIG environment variable
  pkg/info/info.go
  pkg/utils/cluster.go
  pkg/utils/cluster_test.go
  pkg/utils/ocmWrapper.go
  pkg/utils/util_test.go
Labels: lgtm, approved

#17 Clean up naming conventions
  pkg/utils/cluster_test.go
Labels: lgtm, approved

#12 OSD-14688:Migrating Managed scripts
  cmd/ocm-backplane/root.go
  cmd/ocm-backplane/script/describeScript.go
  cmd/ocm-backplane/script/describeScript_test.go
  cmd/ocm-backplane/script/listScripts.go
  cmd/ocm-backplane/script/listScripts_test.go
  cmd/ocm-backplane/script/script.go
  cmd/ocm-backplane/script/script_suite_test.go
Labels: lgtm, approved, jira/valid-reference

#19 OSD-14686: Migrating status command
  cmd/ocm-backplane/root.go
  cmd/ocm-backplane/status/status.go
Labels: lgtm, approved, jira/valid-reference

#20 Migrate backplane-cli: version
  cmd/ocm-backplane/root.go
  cmd/ocm-backplane/version/version.go
  pkg/info/info.go
Labels: lgtm, approved

#24 OSD-14689: Add backplane-cli create and get testjob commands
  Makefile
  cmd/ocm-backplane/root.go
  cmd/ocm-backplane/testJob/createTestJob.go
  cmd/ocm-backplane/testJob/createTestJob_test.go
  cmd/ocm-backplane/testJob/getTestJob.go
  cmd/ocm-backplane/testJob/getTestJobLogs.go
  cmd/ocm-backplane/testJob/getTestJob_test.go
  cmd/ocm-backplane/testJob/testJob.go
  cmd/ocm-backplane/testJob/testJob_suite_test.go
Labels: lgtm, approved, jira/valid-reference

#18 Migrating backplane-cli login & logout
  Makefile
  cmd/ocm-backplane/login/login.go
  cmd/ocm-backplane/login/login_suite_test.go
  cmd/ocm-backplane/login/login_test.go
  cmd/ocm-backplane/logout/logout.go
  cmd/ocm-backplane/logout/logout_test.go
  cmd/ocm-backplane/root.go
  go.mod
  pkg/utils/util.go
Labels: lgtm, approved

#14 OSD-14687: Add Backplane CLI managed jobs add,get,delete,log commands
  Makefile
  cmd/ocm-backplane/managedJob/createManagedJob.go
  cmd/ocm-backplane/managedJob/createManagedJob_test.go
  cmd/ocm-backplane/managedJob/deleteManagedJob.go
  cmd/ocm-backplane/managedJob/deleteManagedJob_test.go
  cmd/ocm-backplane/managedJob/getManagedJob.go
  cmd/ocm-backplane/managedJob/getManagedJob_test.go
  cmd/ocm-backplane/managedJob/logsManagedJob.go
  cmd/ocm-backplane/managedJob/managedJob.go
  cmd/ocm-backplane/managedJob/managedJob_suite_test.go
  cmd/ocm-backplane/root.go
Labels: lgtm, approved, jira/valid-reference

#23 Migrate docs
  README.md
  docs/PS1-setup.md
  docs/design.md
Labels: lgtm, approved

#26 OSD-15356: Onboard codecov.io
  .codecov.yml
  Makefile
  hack/codecov.sh
Labels: lgtm, approved, jira/valid-reference

#27 Add 755 permission to hack scripts
  hack/codecov.sh
Labels: lgtm, approved

#28 Modify test target
  Makefile
  hack/codecov.sh
Labels: lgtm, approved

#29 Fix coverage fails
  Makefile
  cmd/ocm-backplane/testJob/createTestJob_test.go
Labels: lgtm, approved
