Repository openshift/backplane-cli, pull requests merged in 2024-04, with the labels that each got.

#385 Use md5 hash for session name when assuming Org Role in new backplane flow
  cmd/ocm-backplane/cloud/common.go
Labels: lgtm, approved

#387 Update dockerfile to exclude all arch binaries
  Dockerfile
Labels: lgtm, approved

#386 OSD-21419: Fixed console container cleanup issues
  cmd/ocm-backplane/console/console.go
  cmd/ocm-backplane/console/console_test.go
Labels: lgtm, approved, jira/valid-reference

#394 [OSD-21348] Add Test Cases for Helper Function of elevate cmd
  pkg/utils/shell_test.go
Labels: lgtm, approved

#374 OSD-19729: Enables ocm backplane login to provide default namespace as an argument
  README.md
  cmd/ocm-backplane/login/login.go
  cmd/ocm-backplane/login/login_test.go
  docs/PS1-setup.md
  docs/design.md
Labels: lgtm, approved, jira/valid-reference, tide/merge-method-squash

#396 Update golang.org/x/net@v0.24.0
  go.mod
  go.sum
Labels: lgtm, approved

#397 Increase the timeout to get working proxy url
  pkg/cli/config/config.go
Labels: lgtm, approved

#398 Fix typo in debug message
  cmd/ocm-backplane/login/login.go
Labels: lgtm, approved

#399 OSD-21691 : Add domain prefix in place of cluster name for cluster namespace
  cmd/ocm-backplane/login/login.go
  cmd/ocm-backplane/login/login_test.go
Labels: lgtm, approved

#402 [OSD-21438] Remove the fallback to old flow
  cmd/ocm-backplane/cloud/common.go
Labels: lgtm, approved

#401 OSD-22522 elevate allows args with quotes
  pkg/elevate/elevate.go
  pkg/elevate/elevate_test.go
Labels: lgtm, approved

#407 Revert "[OSD-21438] Remove the fallback to old flow"
  cmd/ocm-backplane/cloud/common.go
Labels: lgtm, approved
