Repository openshift/backplane-cli, pull requests merged in 2024-07, with the labels that each got.

#471 stick oc to version 4.15
  Dockerfile
Labels: lgtm, approved

#472 Updates ocm-cli to support OCM_URL environment variable overrides.
  go.mod
  go.sum
Labels: lgtm, approved

#473 Add unit test coverage check when creating a PR
  .github/PULL_REQUEST_TEMPLATE.md
Labels: lgtm, approved

#441 OSD-24268: Determine backplane elevate reason automatically when login via pagerduty incidents
  cmd/ocm-backplane/login/login.go
  cmd/ocm-backplane/login/login_test.go
  pkg/elevate/elevate.go
  pkg/elevate/elevate_context.go
  pkg/elevate/elevate_test.go
  pkg/login/kubeConfig.go
  pkg/pagerduty/pagerduty.go
  pkg/pagerduty/pagerduty_test.go
Labels: lgtm, approved, jira/valid-reference, tide/merge-method-squash

#463 OSD-24127: New accessrequest subcommand used to manage access requests used by the lockbox feature
  Makefile
  cmd/ocm-backplane/accessrequest/accessRequest.go
  cmd/ocm-backplane/accessrequest/createAccessRequest.go
  cmd/ocm-backplane/accessrequest/expireAccessRequest.go
  cmd/ocm-backplane/accessrequest/getAccessRequest.go
  cmd/ocm-backplane/config/set.go
  cmd/ocm-backplane/root.go
  go.mod
  go.sum
  pkg/accessrequest/accessRequest.go
  pkg/accessrequest/accessRequest_test.go
  pkg/cli/config/config.go
  pkg/cli/globalflags/logs.go
  pkg/ocm/mocks/ocmWrapperMock.go
  pkg/ocm/ocmWrapper.go
  pkg/utils/jira.go
  pkg/utils/mocks/jiraMock.go
Labels: lgtm, approved, jira/valid-reference

#478 OSD-24269: Add cluster login support via OHSS card
  Makefile
  cmd/ocm-backplane/login/login.go
  cmd/ocm-backplane/login/login_test.go
  pkg/accessrequest/accessRequest.go
  pkg/accessrequest/accessRequest_test.go
  pkg/jira/issueService.go
  pkg/jira/jira_suite_test.go
  pkg/jira/mocks/jiraMock.go
  pkg/jira/ohssService.go
  pkg/jira/ohssService_test.go
Labels: lgtm, approved, jira/valid-reference, tide/merge-method-squash

#485 Avoid squashing http response err info with unmarshal err
  pkg/utils/util.go
Labels: lgtm, approved

#469 [OSD-19783] Add backplane subcommand to do health check of VPN and proxy
  Makefile
  README.md
  cmd/ocm-backplane/cloud/console.go
  cmd/ocm-backplane/healthcheck/health_check.go
  cmd/ocm-backplane/login/login.go
  cmd/ocm-backplane/root.go
  go.mod
  pkg/cli/config/config.go
  pkg/healthcheck/check_proxy.go
  pkg/healthcheck/check_proxy_test.go
  pkg/healthcheck/check_vpn.go
  pkg/healthcheck/check_vpn_test.go
  pkg/healthcheck/connectivity_checks.go
  pkg/healthcheck/mocks/httpClientMock.go
  pkg/healthcheck/mocks/networkMock.go
Labels: lgtm, approved

#484 Feat: Get version from build info
  Makefile
  cmd/ocm-backplane/version/version.go
  pkg/info/buildInfo.go
  pkg/info/info.go
  pkg/info/info_suite_test.go
  pkg/info/info_test.go
  pkg/info/mocks/buildInfoMock.go
  pkg/info/mocks/infoMock.go
  pkg/utils/util.go
Labels: lgtm, approved

#487 Update to use Ginkgo BDD testing framework to align with the exist test style
  pkg/healthcheck/check_proxy.go
  pkg/healthcheck/check_proxy_test.go
  pkg/healthcheck/check_vpn.go
  pkg/healthcheck/check_vpn_test.go
  pkg/healthcheck/connectivity_checks.go
  pkg/healthcheck/healthcheck_suite_test.go
Labels: lgtm, approved
