Repository openshift/backplane-cli, pull requests merged in 2024-12, with the labels that each got.

#561 Print cluster info aftger login
  README.md
  cmd/ocm-backplane/login/login.go
  pkg/login/printClusterInfo.go
  pkg/login/printClusterInfo_test.go
Labels: lgtm, approved

#580 OSD-27228: Modify tests so that they pass on macOS, fix issue with leaking file
  cmd/ocm-backplane/console/console_test.go
  pkg/elevate/elevate.go
  pkg/elevate/elevate_test.go
Labels: lgtm, approved, jira/valid-reference

#581 Update k8s dependencies
  go.mod
  go.sum
Labels: lgtm, approved, tide/merge-method-squash

#579 [OSD-25707] feat: print api error message
  cmd/ocm-backplane/cloud/common.go
Labels: lgtm, approved

#578 Print cluster info by setting a flag in backplane config file.
  README.md
  cmd/ocm-backplane/login/login.go
  cmd/ocm-backplane/login/login_test.go
  pkg/cli/config/config.go
  pkg/cli/config/config_test.go
Labels: lgtm, approved, tide/merge-method-squash

#553 Add commands to create and delete remediations
  cmd/ocm-backplane/login/login.go
  cmd/ocm-backplane/remediation/remediation.go
  cmd/ocm-backplane/remediation/remediation_test.go
  cmd/ocm-backplane/root.go
  go.mod
  go.sum
  pkg/client/mocks/ClientMock.go
  pkg/client/mocks/ClientWithResponsesMock.go
  pkg/remediation/remediation.go
  pkg/utils/jwt.go
  pkg/utils/jwt_test.go
Labels: lgtm, approved, tide/merge-method-squash

#584 adding beforeStartCleanUp logic to cleanup console pods
  cmd/ocm-backplane/console/console.go
  cmd/ocm-backplane/console/console_test.go
Labels: lgtm, approved
