Repository openshift/backplane-cli, pull requests merged in 2025-05, with the labels that each got.

#672 OSD-29355 : Fix ssm bug which is causing for management clusters following isolated backplane flow
  cmd/ocm-backplane/cloud/ssm.go
  cmd/ocm-backplane/cloud/ssm_test.go
Labels: lgtm, approved

#674 SREP-21: backplane API is now allocating a remediation instance id for each call to createRemediation
  cmd/ocm-backplane/remediation/remediation.go
  cmd/ocm-backplane/remediation/remediation_test.go
  go.mod
  go.sum
  pkg/remediation/remediation.go
Labels: lgtm, approved, jira/valid-reference

#682 Remove filtering the IP whitelist.
  cmd/ocm-backplane/cloud/common.go
  cmd/ocm-backplane/cloud/common_test.go
Labels: lgtm, approved

#684 Add CAD stg and prod IP's to session policy
  cmd/ocm-backplane/cloud/common.go
  cmd/ocm-backplane/cloud/common_test.go
Labels: lgtm, approved

#686 Maint: add comments to clarify the filtering of trusted ips
  cmd/ocm-backplane/cloud/common.go
Labels: lgtm, approved

#692 Make KUBEPS1 warning optional
  cmd/ocm-backplane/login/login.go
  docs/PS1-setup.md
  pkg/cli/config/config.go
Labels: lgtm, approved, tide/merge-method-squash
