Repository openshift/backplane-cli, pull requests merged in 2025-07, with the labels that each got.

#723 Bump sigs.k8s.io/kustomize/api from 0.18.0 to 0.20.0
  go.mod
  go.sum
Labels: lgtm, approved

#716 SREP-711: Add non-interactive command input to ssm command
  README.md
  cmd/ocm-backplane/cloud/ssm.go
  cmd/ocm-backplane/cloud/ssm_test.go
Labels: lgtm, approved, jira/valid-reference, tide/merge-method-squash

#725 [SREP-1063] chore: move console container logic to a dedicated module to improve test
  Makefile
  cmd/ocm-backplane/console/console.go
  cmd/ocm-backplane/console/console_test.go
  pkg/container/common.go
  pkg/container/container.go
  pkg/container/container_docker.go
  pkg/container/container_podman.go
  pkg/container/container_test.go
  pkg/container/factory.go
  pkg/container/mocks/containerEngineMock.go
Labels: lgtm, approved, tide/merge-method-squash

#727 [SREP-993] fix: pass env for 4.17+ monitor plugin
  cmd/ocm-backplane/console/console.go
  cmd/ocm-backplane/console/console_test.go
  pkg/container/container.go
  pkg/container/container_docker.go
  pkg/container/container_podman.go
  pkg/container/container_test.go
  pkg/container/mocks/containerEngineMock.go
Labels: lgtm, approved, tide/merge-method-squash

#724 [SREP-943] docs: add guideline for semver release
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  Makefile
  docs/release.md
Labels: lgtm, approved, tide/merge-method-squash
